using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Compilation;

namespace Nyamu.Tools.CodeExecution
{
    // Wraps UnityEditor.Compilation.AssemblyBuilder: compiles the wrapper source generated by
    // CodeSnippetBuilder into a standalone DLL under Temp/, never touching Assets/ so no domain
    // reload is triggered.
    internal static class CodeCompilerService
    {
        const string OutputRoot = "Temp/Nyamu/CodeExecution";

        public static bool StartBuild(CodeExecutionRecord record, Action<CodeExecutionRecord, CompilerMessage[]> onFinished, out string error)
        {
            if (EditorApplication.isCompiling)
            {
                error = "Unity is compiling.";
                return false;
            }

            var dir = $"{OutputRoot}/{record.Id}";
            try
            {
                Directory.CreateDirectory(dir);
                var sourcePath = $"{dir}/{record.VirtualFileName}";
                File.WriteAllText(sourcePath, record.GeneratedSource, new UTF8Encoding(false));

                var assemblyName = $"Nyamu_Exec_{record.Id}";
                var dllPath = $"{dir}/{assemblyName}.dll";

                var builder = new AssemblyBuilder(dllPath, sourcePath)
                {
                    flags = AssemblyBuilderFlags.EditorAssembly,
                    referencesOptions = ReferencesOptions.UseEngineModules,
                    buildTarget = EditorUserBuildSettings.activeBuildTarget,
                    buildTargetGroup = EditorUserBuildSettings.selectedBuildTargetGroup,
                    additionalDefines = new[] { "NYAMU_CODE_EXECUTION" }
                };

                // ScriptCompilerOptions is a class - mutate the instance AssemblyBuilder already
                // created rather than assigning a fresh one, which would default
                // ApiCompatibilityLevel to NET_2_0 and mismatch the editor assemblies we link against.
                builder.compilerOptions.ApiCompatibilityLevel = ApiCompatibilityLevel.NET_Unity_4_8;
                builder.compilerOptions.CodeOptimization = CodeOptimization.Debug; // emits a .pdb for line-accurate stack traces
                builder.compilerOptions.AllowUnsafeCode = false;

                // Must run after compilerOptions is configured: defaultReferences is derived from
                // it, and SelectReferences has to know which assemblies the builder already brings
                // in on its own.
                builder.additionalReferences = SelectReferences(CollectProjectReferences(), TryGetDefaultReferences(builder));

                record.AssemblyName = assemblyName;
                record.Dir = dir;
                record.DllPath = dllPath;
                record.PdbPath = Path.ChangeExtension(dllPath, ".pdb");

                void OnBuildFinished(string assemblyPath, CompilerMessage[] messages)
                {
                    builder.buildFinished -= OnBuildFinished;
                    onFinished(record, messages);
                }

                builder.buildFinished += OnBuildFinished;
                record.Builder = builder;

                if (!builder.Build())
                {
                    builder.buildFinished -= OnBuildFinished;
                    error = "AssemblyBuilder.Build() returned false. Unity refused to start the build.";
                    return false;
                }

                error = null;
                return true;
            }
            catch (Exception ex)
            {
                error = $"Failed to start compilation: {ex.Message}";
                return false;
            }
        }

        // The references AssemblyBuilder adds on its own. They never appear in
        // additionalReferences, so the dedupe below cannot see them - anything we pass that shares
        // a file name with one of them reaches Roslyn as a second copy of the same assembly.
        static string[] TryGetDefaultReferences(AssemblyBuilder builder)
        {
            try
            {
                return builder.defaultReferences ?? Array.Empty<string>();
            }
            catch
            {
                // Best-effort: SelectReferences still keeps the copy the builder itself uses.
                return Array.Empty<string>();
            }
        }

        internal static IEnumerable<string> CollectProjectReferences()
        {
            var refs = new List<string>();
            foreach (var asm in CompilationPipeline.GetAssemblies(AssembliesType.Editor))
            {
                if (!string.IsNullOrEmpty(asm.outputPath) && File.Exists(asm.outputPath))
                    refs.Add(asm.outputPath);
                if (asm.compiledAssemblyReferences != null)
                    refs.AddRange(asm.compiledAssemblyReferences);
            }

            return refs;
        }

        // Picks one path per assembly file name. Two paths resolving to the same assembly identity
        // produce CS1703 and fail the whole build, and Unity ships every framework facade twice -
        // NetStandard/compat/2.1.0/shims/netstandard/X.dll and
        // UnityReferenceAssemblies/unity-4.8-api/Facades/X.dll - with the project referencing both
        // copies. The result must not depend on the order candidates arrive in, or the collision
        // appears only in some projects.
        internal static string[] SelectReferences(IEnumerable<string> candidates, IEnumerable<string> defaultReferences)
        {
            var defaultFileNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var r in defaultReferences)
                if (!string.IsNullOrEmpty(r))
                    defaultFileNames.Add(Path.GetFileName(r));

            return candidates
                .Where(r => !string.IsNullOrEmpty(r))
                .Where(r => !defaultFileNames.Contains(Path.GetFileName(r)))
                .GroupBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                .Select(g => g.OrderBy(PreferredReferenceOrder).ThenBy(r => r, StringComparer.OrdinalIgnoreCase).First())
                .ToArray();
        }

        // Only reached for a name the exclusion above let through. AssemblyBuilder draws its own
        // framework references from the NetStandard compat profile regardless of
        // ApiCompatibilityLevel, so keep that copy: it matches the builder's path exactly and
        // Roslyn merges the two silently, where the unity-4.8-api facade is a different file whose
        // identity unifies with it - which is what raises CS1703.
        internal static int PreferredReferenceOrder(string path) =>
            path.Replace('\\', '/').IndexOf("/NetStandard/", StringComparison.OrdinalIgnoreCase) >= 0 ? 0 : 1;

        public static void CleanupTempFiles(CodeExecutionRecord record)
        {
            if (string.IsNullOrEmpty(record.Dir))
                return;

            try
            {
                Directory.Delete(record.Dir, true);
            }
            catch
            {
                // Best-effort: Temp/ cleanup failing is not worth surfacing to the agent.
            }
        }
    }
}
