using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Compilation;

namespace Nyamu.Tools.CodeExecution
{
    // Wraps UnityEditor.Compilation.AssemblyBuilder: compiles the wrapper source generated by
    // CodeSnippetBuilder into a standalone DLL under Temp/, never touching Assets/ so no domain
    // reload is triggered.
    internal static class CodeCompilerService
    {
        const string OutputRoot = "Temp/Nyamu/CodeExecution";

        public static bool StartBuild(CodeExecutionRecord record, Action<CodeExecutionRecord, CompilerMessage[]> onFinished, out string error)
        {
            if (EditorApplication.isCompiling)
            {
                error = "Unity is compiling.";
                return false;
            }

            var dir = $"{OutputRoot}/{record.Id}";
            try
            {
                Directory.CreateDirectory(dir);
                var sourcePath = $"{dir}/{record.VirtualFileName}";
                File.WriteAllText(sourcePath, record.GeneratedSource, new UTF8Encoding(false));

                var assemblyName = $"Nyamu_Exec_{record.Id}";
                var dllPath = $"{dir}/{assemblyName}.dll";

                var builder = new AssemblyBuilder(dllPath, sourcePath)
                {
                    flags = AssemblyBuilderFlags.EditorAssembly,
                    referencesOptions = ReferencesOptions.UseEngineModules,
                    buildTarget = EditorUserBuildSettings.activeBuildTarget,
                    buildTargetGroup = EditorUserBuildSettings.selectedBuildTargetGroup,
                    additionalReferences = CollectProjectReferences(),
                    additionalDefines = new[] { "NYAMU_CODE_EXECUTION" }
                };

                // ScriptCompilerOptions is a class - mutate the instance AssemblyBuilder already
                // created rather than assigning a fresh one, which would default
                // ApiCompatibilityLevel to NET_2_0 and mismatch the editor assemblies we link against.
                builder.compilerOptions.ApiCompatibilityLevel = ApiCompatibilityLevel.NET_Unity_4_8;
                builder.compilerOptions.CodeOptimization = CodeOptimization.Debug; // emits a .pdb for line-accurate stack traces
                builder.compilerOptions.AllowUnsafeCode = false;

                record.AssemblyName = assemblyName;
                record.Dir = dir;
                record.DllPath = dllPath;
                record.PdbPath = Path.ChangeExtension(dllPath, ".pdb");

                void OnBuildFinished(string assemblyPath, CompilerMessage[] messages)
                {
                    builder.buildFinished -= OnBuildFinished;
                    onFinished(record, messages);
                }

                builder.buildFinished += OnBuildFinished;
                record.Builder = builder;

                if (!builder.Build())
                {
                    builder.buildFinished -= OnBuildFinished;
                    error = "AssemblyBuilder.Build() returned false. Unity refused to start the build.";
                    return false;
                }

                error = null;
                return true;
            }
            catch (Exception ex)
            {
                error = $"Failed to start compilation: {ex.Message}";
                return false;
            }
        }

        static string[] CollectProjectReferences()
        {
            var refs = new List<string>();
            foreach (var asm in CompilationPipeline.GetAssemblies(AssembliesType.Editor))
            {
                if (!string.IsNullOrEmpty(asm.outputPath) && File.Exists(asm.outputPath))
                    refs.Add(asm.outputPath);
                if (asm.compiledAssemblyReferences != null)
                    refs.AddRange(asm.compiledAssemblyReferences);
            }

            // Dedupe by file name, not full path: two different paths resolving to the same
            // assembly identity produce CS1703 and fail the whole build.
            return refs
                .Where(r => !string.IsNullOrEmpty(r))
                .GroupBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                .Select(g => g.First())
                .ToArray();
        }

        public static void CleanupTempFiles(CodeExecutionRecord record)
        {
            if (string.IsNullOrEmpty(record.Dir))
                return;

            try
            {
                Directory.Delete(record.Dir, true);
            }
            catch
            {
                // Best-effort: Temp/ cleanup failing is not worth surfacing to the agent.
            }
        }
    }
}
